version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - actions
    schedule:
      day: sunday
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "DepBot GH Actions"

  - package-ecosystem: gomod
    directory: "/"
    labels:
      - dependencies
      - actions
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    commit-message:
      prefix: "DepBot Go"